version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - n 21.5.0
      - echo "Installing dependencies..."
      - cd app && npm install
      - cd ..
      #- npm install

  build:
    commands:
      - echo "Building the project..."
      - cd app && npm run build
      - cd ..
      #- npm run build

  post_build:
    commands:
      - echo "Running tests..."
      #- cd ..
      - ls -la
      - cp ./codedeploy/appspec.yml appspec.yml
      #- npm test
    
artifacts:
  files:
    "**/*"